### ISSUE TITLE
Write the problem dynamically

### ISSUE THREAD

**Issue by RodrigoCodeBernardo** [AI-Planning/pddl#57]
Hi,

Is there any example of generating a problem using the information in a python dictionary? Or how to write the problem dynamically?

Thank you very much in advance

**Comment by haz** [comment]
Not sure I follow...what are you looking for beyond what's in the main README?

**Comment by RodrigoCodeBernardo** [comment]
For example, based on this yaml file:

```
types:
  robot: 
    - idmind
  waypoints: 
    - wp1
    - wp2
    - wp3
init:
  robot_at:
    - wp1
  docked:
    - idmind
  dock_at:
    - wp1

goals:  
  visited:
    - wp1
    - wp2
    - wp3
  docked:
    - idmind  
```

I want to generate my problem.pddl file

By now, I have managed to write the whole problem except for the goal. Because it needs a "Formula" data structure.

I leave an excerpt of the code I've done so far.:

```
with open(file_,"rb") as file:
    Dict = yaml.full_load(file)
  
    for item, doc in Dict.items():
        if (item == "types"):
            types = doc
        elif ( item == "init"):
            init = doc 
        elif (item == "goals"):
            goals = doc

    
    if "types" in locals():
        elements_keys = []; objects_ = []
        element = list(types.keys())        
        for x in range(len(element)):
            elements_keys.append(list(types[str(element[x])]))
            for i in range(len(elements_keys)):
                objects_.append(Constant(str(elements_keys[x][i]), type_tags=[str(element[x])]))
    else:
        print("Error types is nod defined in file of config{file_}")
```

```
problem = Problem(
    "problem-1",
    domain=domain,
    requirements=requirements,
    objects= objects_,
    init = init_,
    goal= goals_ ,
)

print(problem_to_string(problem))
```
